# Simple workflow for deploying static content to GitHub Pages

- name: Deploy static content to Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_branch: gh-pages # default: gh-pages